### PR TITLE
Hasher

### PR DESCRIPTION
**Pull request by mohanson**

### CODE REVIEW

**Comment by yejiayu** [comment]
I don't see any code that supports different hash algorithms.

**Comment by mohanson** [comment]
I won't agree to add codes such "support multiple hash algorithm" on master(Keep the master clean and simple). instead, I will open a new branch for cita, This PR provides the ability to achieve cita team's desire.

**Comment by ouwenkg** [comment]
and abi

**Comment by mohanson** [comment]
Give me a five @yejiayu @ouwenkg, This PR just aimed to replace hash algorithm to crate hasher.

**Pull request merged**
